name: First Workflow
on: [push]
  
jobs:
  run-shell-command:
    runs-on: ubuntu-latest
    steps:
      - name: Run a shell command to echo string
        run: echo "Hello, World!"
      - name: Multiline Command
        run: |
          node -v
          npm -v
          echo "This is a multiline command example."

  parallel-job-macos:
    runs-on: macos-latest
    steps:
      - name: View SW Version
        run: sw_vers

  dependent-job:
    runs-on: windows-latest
    needs: run-shell-command
    steps:
      - name: Echo a string
        run: Write-Output "Windows String"